# TODO: consider options for multiple realms
keycloak_server_address: http://localhost:8080
keycloak_client_id: admin-cli
keycloak_realm: master
keycloak_admin_user: admin
keycloak_admin_password: admin
is_container: true
container_name: keycloak_ca_test
target_python_path: "{{ ansible_facts['discovered_interpreter_python'] }}"  #/usr/libexec/platform-python3.6
pip_dependencies:
  - setuptools
  - virtualenv
  - cryptography
  - lxml
  - boto
package_dependencies:
  - unzip
  - openssl
user_name: admin
keycloak_home: /opt/keycloak
role_policy_name: policy
role_policy_description: policy description
path: /opt/keycloak/bin/
failure_factor: 3
max_delta_time_seconds: 900
quarkus_endpoint: example.syslog.endpoint:514
quarkus_protocol: UDP
quarkus_format: UTC
log_console_format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'
action_mail_account: administrator@mail.com
https_truststore_file_path: /opt/keycloak/truststore.jks
https_truststore_password: password
spi_trust_store_file_path: /opt/keycloak/truststore.jks
spi_trust_store_policy: ANY
spi_trust_store_password: password
authentication_flow_id:
jarfile_url: https://maven.pkg.github.com/mitre/keycloak-custom-policies/org/keycloak/policy/password-min-time-policy/0.0.1-SNAPSHOT/password-min-time-policy-0.0.1-20220902.182228-2.jar
flow_alias: example alias
dod_certificate_url: https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/certificates_pkcs7_DoD.zip
https_certificate_files: cert.crt
https_certificate_files_path: /opt/keycloak/conf/cert.crt
https_certificate_key_files: cert.pem
https_certificate_key_files_path: /opt/keycloak/conf/cert.pem
generate_certificates: true
certificate_common_name: keycloak.example.com
certificate_organization_name: U.S. Government
#certificate_subject_alt_names:
#  -
certificate_country_name: US
certificate_organizational_unit: DoD
# If connecting to directory services or other identity provider,
# choose one of the two following configurations for protocol security
#security_option: |
#  https-key-store-file=/opt/keycloak/conf/keystore.jks
#  https-key-store-password=password
# or
security_option: |
  hostname=example.keycloak.com
  https-certificate-file={{ https_certificate_files_path }}
  https-certificate-key-file={{ https_certificate_key_files_path }}
profile_properties_features: |
  feature.account2=disabled
  feature.account_api=disabled
  feature.admin_fine_grained_authz=disabled
  feature.ciba=disabled
  feature.client_policies=disabled
  feature.client_secret_rotation=disabled
  feature.par=disabled
  feature.declarative_user_profile=disabled
  feature.docker=disabled
  feature.impersonation=disabled
  feature.openshift_integration=disabled
  feature.recovery_codes=disabled
  feature.scripts=disabled
  feature.step_up_authentication=disabled
  feature.token_exchange=disabled
  feature.upload_scripts=disabled
  feature.web_authn=disabled
  feature.update_email=disabled
#enabled_event_types:
#  - "SEND_RESET_PASSWORD"
#  - "UPDATE_CONSENT_ERROR"
#  - "GRANT_CONSENT"
#  - "VERIFY_PROFILE_ERROR"
#  - "REMOVE_TOTP"
#  - "REVOKE_GRANT"
#  - "UPDATE_TOTP"
#  - "LOGIN_ERROR"
#  - "CLIENT_LOGIN"
#  - "RESET_PASSWORD_ERROR"
#  - "IMPERSONATE_ERROR"
#  - "CODE_TO_TOKEN_ERROR"
#  - "CUSTOM_REQUIRED_ACTION"
#  - "OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR"
#  - "RESTART_AUTHENTICATION"
#  - "IMPERSONATE"
#  - "UPDATE_PROFILE_ERROR"
#  - "LOGIN"
#  - "OAUTH2_DEVICE_VERIFY_USER_CODE"
#  - "UPDATE_PASSWORD_ERROR"
#  - "CLIENT_INITIATED_ACCOUNT_LINKING"
#  - "TOKEN_EXCHANGE"
#  - "AUTHREQID_TO_TOKEN"
#  - "LOGOUT"
#  - "REGISTER"
#  - "DELETE_ACCOUNT_ERROR"
#  - "CLIENT_REGISTER"
#  - "IDENTITY_PROVIDER_LINK_ACCOUNT"
#  - "DELETE_ACCOUNT"
#  - "UPDATE_PASSWORD"
#  - "CLIENT_DELETE"
#  - "FEDERATED_IDENTITY_LINK_ERROR"
#  - "IDENTITY_PROVIDER_FIRST_LOGIN"
#  - "CLIENT_DELETE_ERROR"
#  - "VERIFY_EMAIL"
#  - "CLIENT_LOGIN_ERROR"
#  - "RESTART_AUTHENTICATION_ERROR"
#  - "EXECUTE_ACTIONS"
#  - "REMOVE_FEDERATED_IDENTITY_ERROR"
#  - "TOKEN_EXCHANGE_ERROR"
#  - "PERMISSION_TOKEN"
#  - "SEND_IDENTITY_PROVIDER_LINK_ERROR"
#  - "EXECUTE_ACTION_TOKEN_ERROR"
#  - "SEND_VERIFY_EMAIL"
#  - "OAUTH2_DEVICE_AUTH"
#  - "EXECUTE_ACTIONS_ERROR"
#  - "REMOVE_FEDERATED_IDENTITY"
#  - "OAUTH2_DEVICE_CODE_TO_TOKEN"
#  - "IDENTITY_PROVIDER_POST_LOGIN"
#  - "IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR"
#  - "OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR"
#  - "UPDATE_EMAIL"
#  - "REGISTER_ERROR"
#  - "REVOKE_GRANT_ERROR"
#  - "EXECUTE_ACTION_TOKEN"
#  - "LOGOUT_ERROR"
#  - "UPDATE_EMAIL_ERROR"
#  - "CLIENT_UPDATE_ERROR"
#  - "AUTHREQID_TO_TOKEN_ERROR"
#  - "UPDATE_PROFILE"
#  - "CLIENT_REGISTER_ERROR"
#  - "FEDERATED_IDENTITY_LINK"
#  - "SEND_IDENTITY_PROVIDER_LINK"
#  - "SEND_VERIFY_EMAIL_ERROR"
#  - "RESET_PASSWORD"
#  - "CLIENT_INITIATED_ACCOUNT_LINKING_ERROR"
#  - "OAUTH2_DEVICE_AUTH_ERROR"
#  - "UPDATE_CONSENT"
#  - "REMOVE_TOTP_ERROR"
#  - "VERIFY_EMAIL_ERROR"
#  - "SEND_RESET_PASSWORD_ERROR"
#  - "CLIENT_UPDATE"
#  - "CUSTOM_REQUIRED_ACTION_ERROR"
#  - "IDENTITY_PROVIDER_POST_LOGIN_ERROR"
#  - "UPDATE_TOTP_ERROR"
#  - "CODE_TO_TOKEN"
#  - "VERIFY_PROFILE"
#  - "GRANT_CONSENT_ERROR"
#  - "IDENTITY_PROVIDER_FIRST_LOGIN_ERROR"
enabled_event_types_string: >
  [ "SEND_RESET_PASSWORD",
  "UPDATE_CONSENT_ERROR",
  "GRANT_CONSENT",
  "VERIFY_PROFILE_ERROR",
  "REMOVE_TOTP",
  "REVOKE_GRANT",
  "UPDATE_TOTP",
  "LOGIN_ERROR",
  "CLIENT_LOGIN",
  "RESET_PASSWORD_ERROR",
  "IMPERSONATE_ERROR",
  "CODE_TO_TOKEN_ERROR",
  "CUSTOM_REQUIRED_ACTION",
  "OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR",
  "RESTART_AUTHENTICATION",
  "IMPERSONATE",
  "UPDATE_PROFILE_ERROR",
  "LOGIN",
  "OAUTH2_DEVICE_VERIFY_USER_CODE",
  "UPDATE_PASSWORD_ERROR",
  "CLIENT_INITIATED_ACCOUNT_LINKING",
  "TOKEN_EXCHANGE",
  "AUTHREQID_TO_TOKEN",
  "LOGOUT",
  "REGISTER",
  "DELETE_ACCOUNT_ERROR",
  "CLIENT_REGISTER",
  "IDENTITY_PROVIDER_LINK_ACCOUNT",
  "DELETE_ACCOUNT",
  "UPDATE_PASSWORD",
  "CLIENT_DELETE",
  "FEDERATED_IDENTITY_LINK_ERROR",
  "IDENTITY_PROVIDER_FIRST_LOGIN",
  "CLIENT_DELETE_ERROR",
  "VERIFY_EMAIL",
  "CLIENT_LOGIN_ERROR",
  "RESTART_AUTHENTICATION_ERROR",
  "EXECUTE_ACTIONS",
  "REMOVE_FEDERATED_IDENTITY_ERROR",
  "TOKEN_EXCHANGE_ERROR",
  "PERMISSION_TOKEN",
  "SEND_IDENTITY_PROVIDER_LINK_ERROR",
  "EXECUTE_ACTION_TOKEN_ERROR",
  "SEND_VERIFY_EMAIL",
  "OAUTH2_DEVICE_AUTH",
  "EXECUTE_ACTIONS_ERROR",
  "REMOVE_FEDERATED_IDENTITY",
  "OAUTH2_DEVICE_CODE_TO_TOKEN",
  "IDENTITY_PROVIDER_POST_LOGIN",
  "IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR",
  "OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR",
  "UPDATE_EMAIL",
  "REGISTER_ERROR",
  "REVOKE_GRANT_ERROR",
  "EXECUTE_ACTION_TOKEN",
  "LOGOUT_ERROR",
  "UPDATE_EMAIL_ERROR",
  "CLIENT_UPDATE_ERROR",
  "AUTHREQID_TO_TOKEN_ERROR",
  "UPDATE_PROFILE",
  "CLIENT_REGISTER_ERROR",
  "FEDERATED_IDENTITY_LINK",
  "SEND_IDENTITY_PROVIDER_LINK",
  "SEND_VERIFY_EMAIL_ERROR",
  "RESET_PASSWORD",
  "CLIENT_INITIATED_ACCOUNT_LINKING_ERROR",
  "OAUTH2_DEVICE_AUTH_ERROR",
  "UPDATE_CONSENT",
  "REMOVE_TOTP_ERROR",
  "VERIFY_EMAIL_ERROR",
  "SEND_RESET_PASSWORD_ERROR",
  "CLIENT_UPDATE",
  "CUSTOM_REQUIRED_ACTION_ERROR",
  "IDENTITY_PROVIDER_POST_LOGIN_ERROR",
  "UPDATE_TOTP_ERROR",
  "CODE_TO_TOKEN",
  "VERIFY_PROFILE",
  "GRANT_CONSENT_ERROR",
  "IDENTITY_PROVIDER_FIRST_LOGIN_ERROR" ]
events_listeners_string: >
  [ "jboss-logging" ]