---
- name: "HIGH | xccdf_hdf_group_KEYC-01-000022_part1 | AUDIT | Keycloak must be configured to use secure protocols when connecting to directory services."
  blockinfile:
    path: /opt/keycloak/conf/keycloak.conf
    block: |
      hostname-strict-https=true
      https-client-auth=required
    state: present
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROTOCOLS"
  register: 22-1
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000022
    - audit

- name: "HIGH | xccdf_hdf_group_KEYC-01-000022_part2 | AUDIT | Keycloak must be configured to use secure protocols when connecting to directory services."
  blockinfile:
    path: /opt/keycloak/conf/keycloak.conf
    block: |
      https-trust-store-file={{https_truststore_file_path}}
      https-trust-store-password=
      {{security_option}}
    state: present
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HTTPS TRUST STORE"
  register: 22-2
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000022
    - audit

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000022 | PATCH | Keycloak must be configured to use secure protocols when connecting to directory services."
#  shell:
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000022
#    - patch

- name: "HIGH | xccdf_hdf_group_KEYC-01-000023_part1 | AUDIT | Keycloak must be configured to use protocols that encrypt credentials when authenticating clients, as defined in the PPSM CAL and vulnerability assessments."
  shell: >
    {{path}}kcadm.sh update realms/{{keycloak_realm}} -s "passwordPolicy='hashAlgorithm(pbkdf2-sha256)'"
  register: 23-1
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000023
    - audit

- name: "HIGH | xccdf_hdf_group_KEYC-01-000023_part2 | AUDIT | Keycloak must be configured to use protocols that encrypt credentials when authenticating clients, as defined in the PPSM CAL and vulnerability assessments."
  blockinfile:
    path: /opt/keycloak/conf/keycloak.conf
    block: |
      cache=ispn
      cache-stack=tcp
    state: present
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - CACHE"
  register: 23-2
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000023
    - audit

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000023 | PATCH | Keycloak must be configured to use protocols that encrypt credentials when authenticating clients, as defined in the PPSM CAL and vulnerability assessments."
#  shell:
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000023
#    - patch

- name: "HIGH | xccdf_hdf_group_KEYC-01-000025_part1 | AUDIT | Keycloak must be configured to uniquely identify and authenticate organizational users."
  shell: >
    {{path}}kcadm.sh create roles -r {{keycloak_realm}} -s name={{role_policy_name}} -s 'description={{role_policy_description}}'
  register: 25-1
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000025
    - audit

- name: "HIGH | xccdf_hdf_group_KEYC-01-000025_part2 | AUDIT | Keycloak must be configured to uniquely identify and authenticate organizational users."
  shell: >
    {{path}}kcadm.sh add-roles --uusername {{user_name}} --rolename {{role_policy_name}} -r {{keycloak_realm}}
  register: 25-2
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000025
    - audit

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000025 | PATCH | Keycloak must be configured to uniquely identify and authenticate organizational users."
#  shell:
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000025
#    - patch

- name: "HIGH | xccdf_hdf_group_KEYC-01-000036 | AUDIT | Keycloak must be configured to encrypt locally stored credentials using a FIPS-validated cryptographic module."
  shell: >
    {{path}}kcadm.sh update realms/{{keycloak_realm}} -s "passwordPolicy='hashAlgorithm(pbkdf2-sha256)'"
  register: 36
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000036
    - audit

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000036 | PATCH | Keycloak must be configured to encrypt locally stored credentials using a FIPS-validated cryptographic module."
#  shell:
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000036
#    - patch

- name: "HIGH | xccdf_hdf_group_KEYC-01-000040_part1 | AUDIT | Keycloak must be configured to only accept certificates issued by a DoD-approved Certificate Authority for PKI-based authentication."
  blockinfile:
    path: /opt/keycloak/conf/keycloak.conf
    block: |
      hostname-strict-https=true
      https-client-auth=required
    state: present
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROTOCOLS"
  register: 40-1
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000040
    - audit

- name: "HIGH | xccdf_hdf_group_KEYC-01-000040_part2 | AUDIT | Keycloak must be configured to only accept certificates issued by a DoD-approved Certificate Authority for PKI-based authentication."
  blockinfile:
    path: /opt/keycloak/conf/keycloak.conf
    block: |
      spi-truststore-file-file={{spi_trust_store_file_path}}
      spi-truststore-file-password=
      spi-truststore-file-hostname-verification-policy={{spi_trust_store_policy}}
    state: present
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SPI TRUST STORE"
  register: 40-2
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - xccdf_hdf_group_KEYC-01-000040
    - audit

# TODO: inspect issuer

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000040 | PATCH | Keycloak must be configured to only accept certificates issued by a DoD-approved Certificate Authority for PKI-based authentication."
#  shell:
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000040
#    - patch

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000041 | AUDIT | Keycloak must be configured to not accept certificates that have been revoked for PKI-based authentication."
#  shell:
#  register: 41
#  check_mode: no
#  changed_when: no
#  ignore_errors: yes
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000041
#    - audit

#- name: "HIGH | xccdf_hdf_group_KEYC-01-000041 | PATCH | Keycloak must be configured to not accept certificates that have been revoked for PKI-based authentication."
#  shell:
#  tags:
#    - cat1
#    - high
#    - xccdf_hdf_group_KEYC-01-000041
#    - patch
#
