- name: Restart Keycloak container
  block:
    - name: Stop
      delegate_to: localhost
      shell: >
        docker stop {{container_name}}

    - name: Pause
      delegate_to: localhost
      wait_for:
        timeout: 5

    - name: Start
      delegate_to: localhost
      shell: >
        docker start {{container_name}}
  tags:
    - xccdf_hdf_group_KEYC-01-000047
    - xccdf_hdf_group_KEYC-01-000048
    - xccdf_hdf_group_KEYC-01-000049
    - xccdf_hdf_group_KEYC-01-000050
    - egress
