---
- name: Show post-password policy string
  ansible.builtin.debug:
    var: password_policy_string

- name: Set password policy
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak_server_address }}"
    auth_client_id: "{{ keycloak_client_id }}"
    realm: "{{ keycloak_realm }}"
    auth_realm: "{{ keycloak_realm }}"
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    state: present
    password_policy: "{{ password_policy_string }}"
  tags:
    - password

- name: Set enabled events types
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak_server_address }}"
    auth_client_id: "{{ keycloak_client_id }}"
    realm: "{{ keycloak_realm }}"
    auth_realm: "{{ keycloak_realm }}"
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    state: present
    enabled_event_types: "{{ enabled_event_types_list }}"

- name: Restart Keycloak container to force changes to take effect
  block:
    - name: Stop container
      delegate_to: localhost
      ansible.builtin.shell: >
        docker stop {{ container_name }}

    - name: Pause
      delegate_to: localhost
      wait_for:
        timeout: 5

    - name: Start container
      delegate_to: localhost
      ansible.builtin.shell: >
        docker start {{ container_name }}
  tags:
    - xccdf_hdf_group_KEYC-01-000047
    - xccdf_hdf_group_KEYC-01-000048
    - xccdf_hdf_group_KEYC-01-000049
    - xccdf_hdf_group_KEYC-01-000050
    - egress
  when: is_container
