- name: Set Up
  shell: /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin
  register: signin

- name: pull jar
  block:
    - name: fetch jar from github
      ansible.builtin.get_url:
        url: "{{jarfile_url}}"
        dest: /tmp/password-min-time-policy-0.0.1.jar
        headers:
          Accept: application/vnd.github+json
          Authorization: "Bearer {{github_pat}}"
      delegate_to: localhost

      vars:
        - jarfile_url: https://maven.pkg.github.com/mitre/keycloak-custom-policies/org/keycloak/policy/password-min-time-policy/0.0.1-SNAPSHOT/password-min-time-policy-0.0.1-20220902.182228-2.jar
        - github_pat:
  tags:
    - xccdf_hdf_group_KEYC-01-000047
