# -*- encoding : utf-8 -*-
control "KEYC-01-000057" do
  title "Keycloak must be configured with a minimum granularity of one second to record time stamps for audit records."
  desc  "
    Without sufficient granularity of time stamps, it is not possible to adequately determine the chronological order of records. 
    
    Time stamps generated by the application include date and time. Granularity of time measurements refers to the degree of synchronization between information system clocks and reference clocks.
  "
  desc  "rationale", ""
  desc  "check", "
    Verify Keycloak are configured with a minimum granularity of one second to record time stamps for audit records.
    
    If Keycloak are not configured with a minimum granularity of one second to record time stamps for audit records, this is a finding.
    
    To confirm this setting is configured using the Keycloak admin CLI, after logging in with a privileged account, which can be done by running:
    
    kcadm.sh config credentials --server [server location] --realm master --user [username] --password [password]
    
    then run the following command:
    
    kcadm.sh get events/config -r [YOUR REALM] 
    
    If the results are not as follows, then it is a finding.
    
    \"eventsEnabled\" : true, 
    \"eventsListeners\" : [ \"jboss-logging\" ],
    \"enabledEventTypes\" : [ APPROPRIATE EVENT TYPES ],
    \"adminEventsEnabled\" : true,
    \"adminEventsDetailsEnabled\" : true
    
    Then inspect recorded time from log messages. If the recorded messages does not use a minimum granularity of one second to record time stamps for audit records entry, this is a finding. 
    
    Then check keycloak configuration file, keycloak.conf. If the file does not contain the following key-value pairs, it is a finding. 
    
    spi-events-listener-jboss-logging-success-level=info
    spi-events-listener-jboss-logging-error-level=error
    log-console-format=\"'%d{[TIME FORMATTING WITH MINIMUM GRANULARITY OF ONE SECOND]} [OTHER FORMATTING SYMBOLS]'\"
  "
  desc  "fix", "
    Configure Keycloak with a minimum granularity of one second to record time stamps for audit records.
    
    To configure this setting using the Keycloak admin CLI, do the following from a privileged account:
    
    kcadm.sh update events/config -r [your realm] -s eventsEnabled=true -s eventsListeners=[\"jboss-logging\"] -s adminEventsEnabled=true -s adminEventsDetailsEnabled=true
    
    Then create or update Keycloak logging format with the following line in your keycloak configuration file, keycloak.conf:
    
    spi-events-listener-jboss-logging-success-level=info
    spi-events-listener-jboss-logging-error-level=error
    log-console-format=\"'%d{yyyy-MM-dd HH:mm:ss,SSS} [OTHER FORMATTING SYMBOLS]'\"
  "
  impact 0.5
  tag severity: "medium"
  tag gtitle: "SRG-APP-000375-AAA-000330"
  tag gid: nil
  tag rid: nil
  tag stig_id: "KEYC-01-000057"
  tag cci: ["CCI-001889"]
  tag nist: ["AU-8 b"]
end