# -*- encoding : utf-8 -*-
control "KEYC-01-000056" do
  title "Keycloak must be configured to use or map to Coordinated Universal Time (UTC) to record time stamps for audit records."
  desc  "
    If time stamps are not consistently applied and there is no common time reference, it is difficult to perform forensic analysis.
    
    Time stamps generated by the application include date and time. Time is commonly expressed in Coordinated Universal Time (UTC) or local time with an offset from UTC.
  "
  desc  "rationale", ""
  desc  "check", "
    Verify Keycloak are configured to use or map to UTC to record time stamps for audit records. The audit records must either show UTC time or an offset to UTC time for each entry.
    
    If Keycloak are not configured to use or map to UTC to record time stamps for audit records, this is a finding.
    
    To confirm this setting is configured using the Keycloak admin CLI, after logging in with a privileged account, which can be done by running:
    
    kcadm.sh config credentials --server [server location] --realm master --user [username] --password [password]
    
    then run the following command:
    
    kcadm.sh get events/config -r [YOUR REALM] 
    
    If the results are not as follows, then it is a finding.
    
    \"eventsEnabled\" : true, 
    \"eventsListeners\" : [ \"jboss-logging\" ],
    \"enabledEventTypes\" : [ APPROPRIATE EVENT TYPES ],
    \"adminEventsEnabled\" : true,
    \"adminEventsDetailsEnabled\" : true
    
    Then inspect recorded time from log messages. If the recorded messages do not use Coordinated Universal Time (UTC) or an offset to UTC time for entry, this is a finding. 
    
    Then check keycloak configuration file, keycloak.conf. If the file does not contain the following key-value pairs, it is a finding. 
    
    spi-events-listener-jboss-logging-success-level=info
    spi-events-listener-jboss-logging-error-level=error
    log-console-format=\"'%z{[UTC OR AN OFFSET TO UTC]} [OTHER FORMATTING SYMBOLS]'\"
  "
  desc  "fix", "
    Configure Keycloak to use or map to UTC to record time stamps for audit records.
    
    To configure this setting using the Keycloak admin CLI, do the following from a privileged account:
    
    kcadm.sh update events/config -r [your realm] -s eventsEnabled=true -s 'eventsListeners=[\"jboss-logging\"] -s adminEventsEnabled=true -s adminEventsDetailsEnabled=true
    
    Then create or update Keycloak logging format with the following line in your keycloak configuration file, keycloak.conf:
    
    spi-events-listener-jboss-logging-success-level=info
    spi-events-listener-jboss-logging-error-level=error
    log-console-format=\"'%z{UTC} [OTHER FORMATTING SYMBOLS]'\"
    
  "
  impact 0.5
  tag severity: "medium"
  tag gtitle: "SRG-APP-000374-AAA-000340"
  tag gid: nil
  tag rid: nil
  tag stig_id: "KEYC-01-000056"
  tag cci: ["CCI-001890"]
  tag nist: ["AU-8 b"]
end